name: 部署到GitHub Pages

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: 构建发布版本
      run: |
        python scripts/publication-preparer.py --version ${GITHUB_REF#refs/tags/}
        python scripts/distribution-setup.py
    
    - name: 设置Pages
      uses: actions/configure-pages@v3
    
    - name: 上传构建产物
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: 部署到GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2