name: 质量检查

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: 文档格式检查
      run: |
        python scripts/format-standardization.py --dry-run
    
    - name: 样式验证
      run: |
        python scripts/style-validator.py
    
    - name: 交叉引用检查
      run: |
        python scripts/cross-reference-validator.py
    
    - name: 图表质量检查
      run: |
        python scripts/chart-quality-validator.py
    
    - name: 设备兼容性测试
      run: |
        python scripts/device-compatibility-tester.py
    
    - name: 上传质量报告
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: quality-reports
        path: |
          *-report.md
          *.json